#!/bin/sh

# This is the ceramic install script!
#
# MAC AND LINUX:
#   Just open up your terminal and type:
#
#     curl -L URL | sh
#

if [ "$UNAME" = "Darwin" ] ; then
    curl -L https://github.com/ceramic-engine/ceramic/releases/download/dev01/ceramic.zip -o ceramic.zip
    unzip ceramic.zip
    rm ceramic.zip
    cd ceramic/tools
    ./ceramic link
    cd ../..
    ceramic
fi
