#!/bin/bash
cd "${0%/*}"

# Install haxe stuff and build ceramic tools
haxelib install hxcpp --always || exit 1
haxelib install tools.hxml --always || exit 1
haxe tools.hxml || exit 1
haxe tools-luxe.hxml || exit 1