platform :ios, '11.0'
use_frameworks!

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

target 'MyApp' do
  #pod 'SomePodDependencyName', '~> 1.0'

  # BEGIN CERAMIC PODS
  # END CERAMIC PODS
end
