#include "audio_worklets.h"

#include <atomic>

// Generated by reflaxe.CPP from the extracted worklet sources
// (the include path must point to the generated `include` directory)
#include "Main.h"
#include "backend_Audio.h"

#define AUDIO_WORKLETS_MAX_BUSES 32

// This glue is only a C ABI forwarder: the synchronization between the
// control functions (main thread) and the processing (audio thread) lives
// in the transpiled `ceramic.AudioFilters`, which is the very same code the
// hxcpp host runs — one implementation, one behaviour.

namespace {

    inline bool validBus(int bus) {
        return bus >= 0 && bus < AUDIO_WORKLETS_MAX_BUSES;
    }

}

extern "C" {

void audio_worklets_init(void) {
    // Runs the generated haxe main(), which registers the worklet
    // factory with backend::Audio (the generated `_main_.cpp` C entry
    // point is NOT compiled into this library)
    _Main::Main_Fields_::main();
}

int audio_worklets_add_bus_filter(int bus, int filterId, const char* workletClass) {
    if (!validBus(bus)) return 0;
    return backend::Audio::addBusFilter(bus, filterId, std::string(workletClass)) ? 1 : 0;
}

void audio_worklets_destroy_bus_filter(int bus, int filterId) {
    if (!validBus(bus)) return;
    backend::Audio::destroyBusFilter(bus, filterId);
}

void audio_worklets_set_params(int bus, int filterId, const float* values, int count) {
    if (!validBus(bus)) return;
    backend::Audio::setParams(bus, filterId, const_cast<float*>(values), count);
}

int audio_worklets_filter_ready(int bus, int filterId) {
    if (!validBus(bus)) return 0;
    return backend::Audio::isFilterReady(bus, filterId) ? 1 : 0;
}

void audio_worklets_process_bus(int bus, float* buffer, unsigned int samples,
                                unsigned int channels, float sampleRate, double time) {
    if (!validBus(bus)) return;
    backend::Audio::processBus(bus, buffer, (int)samples, (int)channels, (double)sampleRate, time);
}

/* --- Host integration helpers -------------------------------------------- */

static std::atomic<int> g_busInstanceReady[AUDIO_WORKLETS_MAX_BUSES];

void audio_worklets_clay_create(int busIndex, int instanceId) {
    (void)instanceId;
    if (validBus(busIndex)) {
        g_busInstanceReady[busIndex].store(1);
    }
}

void audio_worklets_clay_destroy(int busIndex, int instanceId) {
    (void)instanceId;
    if (validBus(busIndex)) {
        g_busInstanceReady[busIndex].store(0);
    }
}

void audio_worklets_clay_process(int busIndex, int instanceId, float* aBuffer,
                                 unsigned int aSamples, unsigned int aChannels,
                                 float aSamplerate, double time) {
    (void)instanceId;
    audio_worklets_process_bus(busIndex, aBuffer, aSamples, aChannels, aSamplerate, time);
}

int audio_worklets_clay_bus_ready(int busIndex) {
    if (validBus(busIndex)) {
        return g_busInstanceReady[busIndex].load();
    }
    return 0;
}

}
