#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
if [ "$(uname)" == "Darwin" ]; then
    "$SCRIPT_DIR"/../git/haxe-binary/mac/haxe/haxe "$@"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    if [ "$(uname -m)" == "aarch64" ]; then
        "$SCRIPT_DIR"/../git/haxe-binary/linux-arm64/haxe/haxe "$@"
    else
        "$SCRIPT_DIR"/../git/haxe-binary/linux-64/haxe/haxe "$@"
    fi
fi