#!/bin/bash
export PATH=${0%/*}':'$PATH
if [ "$(uname)" == "Darwin" ]; then
    export PATH=${0%/*}/../git/haxe-binary/mac/neko':'$PATH
    export PATH=${0%/*}/../git/haxe-binary/mac/haxe':'$PATH
    export HAXEPATH=${0%/*}/../git/haxe-binary/mac/haxe
    export HAXE_STD_PATH=${0%/*}/../git/haxe-binary/mac/haxe/std
    export HAXELIB_PATH=${0%/*}/../.haxelib
    export NEKOPATH=${0%/*}/../git/haxe-binary/mac/neko
    export DYLD_FALLBACK_LIBRARY_PATH=${0%/*}/../git/haxe-binary/mac/neko
    # Unfortunately this is needed to ensure self-contained haxe work, 
    # because haxe can call haxelib internally and environment variables
    # to locate neko don't seem to propagate. As a workaround we ensure neko
    # libs are available from /usr/local/lib so that 'haxelib called from haxe' will find them
    if [ ! -d "/usr/local/lib" ]; then
        mkdir -p /usr/local/lib
    fi
    if [ ! -d "/usr/local/lib/neko" ]; then
        ln -s $NEKOPATH                      /usr/local/lib/neko
    fi
    if [ ! -f "/usr/local/lib/libneko.dylib" ]; then
        ln -s $NEKOPATH/libneko.dylib        /usr/local/lib/libneko.dylib
        ln -s $NEKOPATH/libneko.2.1.0.dylib  /usr/local/lib/libneko.2.1.0.dylib
        ln -s $NEKOPATH/libneko.2.dylib      /usr/local/lib/libneko.2.dylib
    fi
    "${0%/*}"/../git/haxe-binary/mac/haxe/haxe "$@"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    export PATH=${0%/*}/git/haxe-binary/linux/neko':'$PATH
    export PATH=${0%/*}/git/haxe-binary/linux/haxe':'$PATH
    export HAXEPATH=${0%/*}/../git/haxe-binary/linux/haxe
    export HAXE_STD_PATH=${0%/*}/../git/haxe-binary/linux/haxe/std
    export HAXELIB_PATH=${0%/*}/../.haxelib
    export NEKOPATH=${0%/*}/../git/haxe-binary/linux/neko
    export DYLD_FALLBACK_LIBRARY_PATH=${0%/*}/../git/haxe-binary/linux/neko
    if [ ! -d "/usr/local/lib" ]; then
        mkdir -p /usr/local/lib
    fi
    if [ ! -d "/usr/local/lib/neko" ]; then
        ln -s $NEKOPATH                      /usr/local/lib/neko
    fi
    if [ ! -f "/usr/local/lib/libneko.so" ]; then
        ln -s $NEKOPATH/libneko.so           /usr/local/lib/libneko.so
        ln -s $NEKOPATH/libneko.so.2.2.0     /usr/local/lib/libneko.so.2.2.0
        ln -s $NEKOPATH/libneko.so.2         /usr/local/lib/libneko.so.2
    fi
    "${0%/*}"/../git/haxe-binary/linux/haxe/haxe "$@"
fi