#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    "${0%/*}"/../git/haxe-binary/mac/haxe/haxelib "$@"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    "${0%/*}"/../git/haxe-binary/linux/haxe/haxelib "$@"
fi